version: '3.3'
services:
  x:
    build: x
    volumes:
      - './x/app:/app'
      - './volumes/x/logs:/app/logs'
    ports:
      - '5900:5900'
  fluxbox:
    build: fluxbox
    depends_on:
      - x
    volumes:
      - './fluxbox/app:/app'
  dosbox:
    build: dosbox
    volumes:
      - './dosbox/app:/app'
      - './dosbox/root/dotdosbox:/root/.dosbox'
    depends_on:
      - x
  x2txt:
    build: x2txt
    ports:
      - '8080:8080'
    volumes:
      - './x2txt/app:/app'
      - './volumes/x2txt/images:/images'
      - './volumes/x2txt/ocr:/ocr'
      - './volumes/x2txt/logs:/logs'
    depends_on:
      - x
